DotNet/TheatreCMS/Models/RentalRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace TheatreCMS.Models
{
    public class RentalRequest
    {
        [Key]
        public int RentalRequestId { get; set; }    // rental request primary key

        [StringLength(40, ErrorMessage = "Error. This field is limited to 40 characters.")]
        [Display(Name = "Contact Person")]
        public string ContactPerson { get; set; }   // name for point of contact

        [Required(ErrorMessage = "Please provide a valid phone number")]
        [Display(Name = "Contact Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string ContactPhoneNumber { get; set; }

        [Display(Name = "Contact Email address")]
        [Required(ErrorMessage = "Please provide a valid email address")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string ContactEmail { get; set; }

        [StringLength(100, ErrorMessage = "Error. This field is limited to 100 characters.")]
        public string Company { get; set; }         // company requesting the rental

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        [Display(Name = "Start Time")]
        public DateTime StartTime { get; set; }     // rental start date and time

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        [Display(Name = "End Time")]
        public DateTime EndTime { get; set; }       // rental end date and time

        [Display(Name = "Project Info")]
        [StringLength(2000, ErrorMessage = "Error. This field is limited to 2000 characters.")]
        public string ProjectInfo { get; set; }     // info on the project using the space

        [StringLength(1000, ErrorMessage = "Error. This field is limited to 1000 characters.")]
        public string Requests { get; set; }        // special requests for rental

        [Display(Name = "Rental Code")]
        public int RentalCode { get; set; }         // rental confirmation number

        [Display(Name = "Accepted")]
        public bool Accepted { get; set; }          // rental request approved

        [Display(Name = "Contract Signed")]
        public bool ContractSigned { get; set; }    // rental contract signed by both parties




       }

    }

DotNet/TheatreCMS/Controllers/RentalRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheatreCMS.Models;

namespace TheatreCMS.Controllers
{
    public class RentalRequestController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RentalRequest
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.RentalRequests.ToList());
        }

        public void RentalAddCalendar(RentalRequest rentalRequest)
        {
            CalendarEvent calendar = new CalendarEvent();

            calendar.RentalRequestId = rentalRequest.RentalRequestId;
            calendar.Title = rentalRequest.Company;
            calendar.StartDate = rentalRequest.StartTime;
            calendar.EndDate = rentalRequest.EndTime;
            db.CalendarEvent.Add(calendar);
            db.SaveChanges();

        }

        public void RentalEditCalendar(RentalRequest rentalRequest)
        {

            CalendarEvent calendar = db.CalendarEvent.Where(x => x.RentalRequestId == rentalRequest.RentalRequestId).FirstOrDefault();

            if (calendar == null)
            {
                RentalAddCalendar(rentalRequest);
            }
            else if (rentalRequest.RentalRequestId == calendar.RentalRequestId)
            {
                calendar.Title = rentalRequest.Company;
                calendar.StartDate = rentalRequest.StartTime;
                calendar.EndDate = rentalRequest.EndTime;
                db.Entry(calendar).State = EntityState.Modified;
                db.SaveChanges();
            }

        }

        public void RentalDeleteCalendar(RentalRequest rentalRequest)
        {
            CalendarEvent calendar = db.CalendarEvent.Where(x => x.RentalRequestId == rentalRequest.RentalRequestId).FirstOrDefault();
            if (calendar != null)
            {
                db.CalendarEvent.Remove(calendar);
                db.SaveChanges();
            }

        }


        // GET: RentalRequest/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            if (rentalRequest == null)
            {
                return HttpNotFound();
            }
            return View(rentalRequest);
        }

        // GET: RentalRequest/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RentalRequest/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RentalRequestId,ContactPerson,ContactPhoneNumber,ContactEmail,Company,StartTime,EndTime,ProjectInfo,Requests,RentalCode,Accepted,ContractSigned")] RentalRequest rentalRequest)
        {
            long sec = 10000000;        //DateTime ticks per second
            long hrSecs = 3600;         //Seconds in an hour
            long Strtm = Convert.ToInt64(rentalRequest.StartTime.Ticks) / sec;    //divided ticks into seconds
            long Endtm = Convert.ToInt64(rentalRequest.EndTime.Ticks) / sec;
            if (Endtm < (Strtm + hrSecs) && Endtm >= Strtm)    //Doesn't allow rentals < 1hr
            {
                ModelState.AddModelError("EndTime", "** Rental must be at least 1 hour.  **");  
            }
            if (Endtm < Strtm)   //Keeps End time after start time
            {
                ModelState.AddModelError("StartTime", "** Start Time cannot occur after End Time.  **");
            }
            if (ModelState.IsValid)
            {
                db.RentalRequests.Add(rentalRequest);
                var randomNum = new Random();
                int codeNum = randomNum.Next(10000, 99999);
                rentalRequest.RentalCode = codeNum;
                db.SaveChanges();
                if (rentalRequest.Accepted == true)
                {
                    RentalAddCalendar(rentalRequest);
                }
                return RedirectToAction("Index");
            }

            return View(rentalRequest);
        }

        // GET: RentalRequest/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            if (rentalRequest == null)
            {
                return HttpNotFound();
            }
            return View(rentalRequest);
        }

        // POST: RentalRequest/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "RentalRequestId,ContactPerson,ContactPhoneNumber,ContactEmail,Company,StartTime,EndTime,ProjectInfo,Requests,Accepted,ContractSigned")] RentalRequest rentalRequest)
        {
            long sec = 10000000;        //DateTime ticks per second
            long hrSecs = 3600;         //Seconds in an hour
            long Strtm = Convert.ToInt64(rentalRequest.StartTime.Ticks) / sec;    //divided ticks into seconds
            long Endtm = Convert.ToInt64(rentalRequest.EndTime.Ticks) / sec;
            if (Endtm < (Strtm + hrSecs) && Endtm >= Strtm)    //Doesn't allow rentals < 1hr
            {
                ModelState.AddModelError("EndTime", "** Rental must be at least 1 hour.  **");
            }
            if (Endtm < Strtm)   //Keeps End time after start time
            {
                ModelState.AddModelError("StartTime", "** Start Time cannot occur after End Time.  **");
            }
            if (ModelState.IsValid)
            {

                var currentRentalRequest = db.RentalRequests.Find(rentalRequest.RentalRequestId);

                currentRentalRequest.ContactPerson = rentalRequest.ContactPerson;
                currentRentalRequest.ContactPhoneNumber = rentalRequest.ContactPhoneNumber;
                currentRentalRequest.ContactEmail = rentalRequest.ContactEmail;
                currentRentalRequest.Company = rentalRequest.Company;
                currentRentalRequest.StartTime = rentalRequest.StartTime;
                currentRentalRequest.EndTime = rentalRequest.EndTime;
                currentRentalRequest.ProjectInfo = rentalRequest.ProjectInfo;
                currentRentalRequest.Requests = rentalRequest.Requests;
                currentRentalRequest.Accepted = rentalRequest.Accepted;
                currentRentalRequest.ContractSigned = rentalRequest.ContractSigned;

                db.Entry(currentRentalRequest).State = EntityState.Modified;
                db.SaveChanges();

                if (rentalRequest.Accepted == true)
                {
                    RentalEditCalendar(rentalRequest);
                }
                else if (rentalRequest.Accepted == false)
                {
                    RentalDeleteCalendar(rentalRequest);
                }
                return RedirectToAction("Index");
            }
            return View(rentalRequest);
        }

        // GET: RentalRequest/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            if (rentalRequest == null)
            {
                return HttpNotFound();
            }
            return View(rentalRequest);
        }

        // POST: RentalRequest/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            if (rentalRequest.Accepted == true)
            {
                RentalDeleteCalendar(rentalRequest);
            }
            db.RentalRequests.Remove(rentalRequest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RequestConfirm()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult GetRentalEvents()
        {
            var events = db.RentalRequests.ToArray();

            return Json(db.RentalRequests.Select(x => new
            {
                rentalRequestId = x.RentalRequestId,
                contactPerson = x.ContactPerson,
                company = x.Company,
                start = x.StartTime,
                end = x.EndTime,               
                projectInfo = x.ProjectInfo,
                requests = x.Requests,
                rentalCode= x.RentalCode,
                accepted = x.Accepted,
                contractSigned = x.ContractSigned,
                allDay = false,
               
            }).ToArray(), JsonRequestBehavior.AllowGet);
        }

        

    }
} 

DotNet/TheatreCMS/Views/RentalRequest/Create.cshtml
@model TheatreCMS.Models.RentalRequest



@{
    ViewBag.Title = "Create Rental Request";
}




@using (Html.BeginForm())
{

    if (User.IsInRole("Admin"))
    {
        <div class="text-center">
            <br />@Html.ActionLink("All Rental Requests", "Index")
        </div>
    }
    @Html.AntiForgeryToken()
    <div class="formContainer2 ">
        <div class="form-horizontal">
            <h4 class="formHeader">Create Rental Request</h4>
            <hr />

            <div class="inputBox2">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ContactPerson, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.ContactPerson, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContactPerson, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ContactPhoneNumber, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.ContactPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContactPhoneNumber, "", new { @class = "text-white" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ContactEmail, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.ContactEmail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContactEmail, "", new { @class = "text-white" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-white" }) @*Changed to text white because of red background on page*@
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-white" }) @*Changed to text white because of red background on page*@
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectInfo, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.ProjectInfo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProjectInfo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Requests, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.Requests, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Requests, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
        @Html.LabelFor(model => model.Attachments, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.Attachments, new { type = "file" })
            @Html.ValidationMessageFor(x => x.Attachments)
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
         </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Accepted, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Accepted)
                            @Html.ValidationMessageFor(model => model.Accepted, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ContractSigned, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.ContractSigned)
                            @Html.ValidationMessageFor(model => model.ContractSigned, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 formBox">
                        <input type="submit" value="Submit" class="submitButton2" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}




@*Html.DisplayFor(model => model.EndTime)
    @{
        if (Model.EndTime < Model.StartTime)
        {
            @Html.ValidationMessageFor(model => model.EndTime, "Please enter an end time at least an hour after start time", new { @class = "text-info" })
        }
        else
        {
            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-info" })
        }
    }*@

DotNet/TheatreCMS/Views/RentalRequest/Delete.cshtml
@model TheatreCMS.Models.RentalRequest

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RentalRequest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Requests)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Requests)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RentalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Accepted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Accepted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContractSigned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContractSigned)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DotNet/TheatreCMS/Views/RentalRequest/Index.cshtml
@model IEnumerable<TheatreCMS.Models.RentalRequest>

@{
  ViewBag.Title = "Rental Request";
}

<div class="container-fluid">
  <div class="m-4">
    @*IDJ--Took the h2 out of class tag so that the btn wasnt styled with the header tag*@
    <h2 id="Isaiah_RentalHeader">Rental Requests</h2>@*IDJ--Gave this header an id so that using css i can place a btn next to it*@

    @*Calendar toggle button*@
    @*Adds spacing between icons*@
    <button id="toggleCal" onclick="toggleIcon(this)" class="calIcon fa fa-calendar-minus m-2"></button>

    @*IDJ--Making a btn that matches in styling with the other buttons on this page that links to the RentalRequest create page*@
    @*Adds spacing between icons*@
    <a class="Isaiah_pillBtn badge badge-pill badge-danger text-black m-2" href="@Url.Action("Create", "RentalRequest")">Create</a>
  </div>

  @*Calendar divs*@
  <div id="rentalCalendar" class="rentEventCalendar">
    <div class="calendar-body">
      <div id="rentalCalendarInner"></div>
    </div>
  </div>
</div>

<div class="mt-5"></div>
<table class=" table-responsive-stack" id="rentalRequests">
  <thead class="bg-light">
    <tr class="text-black">
      <th>
          @Html.DisplayNameFor(model => model.ContactPerson)
      </th>
      <th>
          @Html.DisplayNameFor(model => model.Company)
      </th>
      <th>
          @Html.DisplayNameFor(model => model.StartTime)
      </th>
      <th>
          @Html.DisplayNameFor(model => model.EndTime)
      </th>
      <th>
          @Html.DisplayNameFor(model => model.ProjectInfo)
      </th>
      <th>
          @Html.DisplayNameFor(model => model.Requests)
      </th>
      <th>
          @Html.DisplayNameFor(model => model.RentalCode)
      </th>
      <th>
          @Html.DisplayNameFor(model => model.Accepted)
      </th>
      <th>
          @Html.DisplayNameFor(model => model.ContractSigned)
      </th>
      <th class="bg-black border-0" id="rental-request-nav-th">
          <div class="hidden-placeholder"></div>
      </th>
    </tr>
  </thead>

  <tbody>
    @{
      string rentalStartDate;
      string rentalStartTime;
      string rentalEndDate;
      string rentalEndTime;

      foreach (var item in Model)
      {
        rentalStartDate = item.StartTime.ToString("dd-MM-yy");
        rentalStartTime = item.StartTime.ToString("HH:mm tt");
        rentalEndDate = item.EndTime.ToString("dd-MM-yy");
        rentalEndTime = item.EndTime.ToString("HH:mm tt");

        <tr class="text-light rental-request-rows">
          <td>
            @Html.DisplayFor(modelItem => item.ContactPerson)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.Company)
          </td>
          <td>
            <div class="rental-request-date">@rentalStartDate</div>
            <div class="rental-request-date">@rentalStartTime</div>
          </td>
          <td>
            <div class="rental-request-date">@rentalEndDate</div>
            <div class="rental-request-date">@rentalEndTime</div>
          </td>
          <td id="rental-request-project-info">
            <button type="button" class="project-info-popover fa fa-search" title="Project Info" data-trigger="hover" data-toggle="project-info" data-content="@Html.DisplayFor(modelItem => item.ProjectInfo)"></button>
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.Requests)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.RentalCode)
          </td>
          <td>
            @if (item.Accepted)
            {
                <span class="text-success">Yes</span>
            }
            else
            {
                <span class="text-danger">No</span>
            }
            @*Html.DisplayFor(modelItem => item.Accepted)*@
          </td>
          <td>
            @if (item.ContractSigned)
            {
                <span class="text-success">Yes</span>
            }
            else
            {
                <span class="text-danger">No</span>
            }
            @*Html.DisplayFor(modelItem => item.ContractSigned)*@
          </td>
          <td id="rental-request-nav-container">
            <div class="rental-request-nav">@Html.ActionLink("Edit", "Edit", new { id = item.RentalRequestId }, new { @class = "badge badge-pill badge-danger text-black" }) </div>
            <div class="rental-request-nav">@Html.ActionLink("Details", "Details", new { id = item.RentalRequestId }, new { @class = "badge badge-pill badge-danger text-black" }) </div>
            <div class="rental-request-nav">@Html.ActionLink("Delete", "Delete", new { id = item.RentalRequestId }, new { @class = "badge badge-pill badge-danger text-black" }) </div>
          </td>
        </tr>
      }
    }

  </tbody>
</table>

@*Handles stacking when resolution < 992->*@
@Scripts.Render("~/bundles/jquery")
<script src="@Url.Content("~/Scripts/umd/popper.min.js")"></script>
<script>
  $(document).ready(function () {

    $('[data-toggle="project-info"]').popover();

    $('.table-responsive-stack').find("th").each(function (i) {
      if (!$(this).is('#rental-request-nav-th')) {
        $('.table-responsive-stack td:nth-child(' + (i + 1) + ')').prepend('<div class="table-responsive-stack-thead">' + $(this).text() + '</div><br>');
      }
      $('.table-responsive-stack-thead').hide();
    });


    $('.table-responsive-stack').each(function () {
      var thCount = $(this).find("th").length;
      var rowGrow = 100 / thCount + '%';
      $(this).find("th, td").css('flex-basis', rowGrow);
    });

    function flexTable() {
      if (window.matchMedia('(max-width: 992px)').matches) {

        $(".table-responsive-stack").each(function (i) {
          $(this).find(".table-responsive-stack-thead").show();
          $(this).find('thead').hide();
        });

        $(".project-info-popover").each(function (i) {
          $(this).replaceWith('<span class="mobile-project-info">' + $(this).attr("data-content") + '</span>');
        });



      } else {

        $(".table-responsive-stack").each(function (i) {
          $(this).find(".table-responsive-stack-thead").hide();
          $(this).find('thead').show();
        });

        $(".mobile-project-info").each(function (i) {
          $(this).replaceWith('<button type="button" class="project-info-popover fa fa-search" title="Project Info" data-trigger="hover" data-toggle="project-info" data-content="' + $(this).text() + '"></button>');
        });
        $('[data-toggle="project-info"]').popover();
      }
    }

    flexTable();

    window.onresize = function (event) {

      flexTable();
    };

    $('.rental-request-rows').hover(
      function () {
        $(this).find('.rental-request-nav').fadeTo(400, 1);
      },
      function () {
        $(this).find('.rental-request-nav').fadeTo(400, 0);
      }
    );

  });
</script>

DotNet/TheatreCMS/Views/RentalRequest/RequestConfirm.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<div id="giraffe" class="container text-left">

    <div class="container">
        <div class="w3-container w3-black text-center">
            <br />
            <br />
            <br />
            <h1 class="thanks">Thank You</h1>
            <br />
            <br />
            <br>
            <br>
        </div>
        <div>

            <h2 class="bigger lead text-light text-center">Request Reference #108 Has Been Confirmed!</h2>
            <h3 class="bigger lead text-light text-center">Please email any additional documentation to rentals@theatrevertigo.org </h3>
            <br>
            <br />
         
        </div>
    </div>
</div>