DotNet/TheatreCMS/Models/Sponsor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace TheatreCMS.Models
{
    public class Sponsor
    {
        [Key]
        public int SponsorId { get; set; }  // sponsor primary key
        public string Name { get; set; }    // sponsor name
        [Display(Name ="Logo Image")]       
        public int LogoId { get; set; }     // ID of photo.cs object
        public int? Height { get; set; }    // logo display height (may be different from original)
        public int? Width { get; set; }     // logo display width (may be different from original)
        public bool Current { get; set; }   // active sponsor
        public string Link { get; set; }        //url of sponsor website
    }
} 

DotNet/TheatreCMS/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheatreCMS.Models;
using System.Diagnostics;

namespace TheatreCMS.Controllers
{
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: list of Published News
        public ActionResult Published()
        {
            if (User.IsInRole("Admin"))
            {
                return View(db.News.OrderByDescending(i => i.LastSaveDate).ToList());
            }
            else
            {
                return View(db.News.Where(i => i.PublishDate != null && i.Hidden == false).OrderByDescending(i => i.PublishDate).ToList());
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: News
        public ActionResult Index()
        {
            return View(db.News.ToList());
        }

        [Authorize(Roles = "Admin")]
        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            news.Headline = HttpUtility.HtmlDecode(news.Headline);
            news.Content = HttpUtility.HtmlDecode(news.Content);
            return View(news);
        }

        [Authorize(Roles = "Admin")]
        // GET: News/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NewsId,Headline,Content,PublishDate,EmailDate,Hidden")] News news)
        {
            if (ModelState.IsValid)
            {
                news.Headline = HttpUtility.HtmlEncode(news.Headline);
                news.Content = HttpUtility.HtmlEncode(news.Content);
                news.CreateDate = DateTime.Now;
                news.LastSaveDate = DateTime.Now;
                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Published");
            }

            return View(news);
        }

        [Authorize(Roles = "Admin")]
        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            news.Headline = HttpUtility.HtmlDecode(news.Headline);
            news.Content = HttpUtility.HtmlDecode(news.Content);
            return View(news);
        }

        [Authorize(Roles = "Admin")]
        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NewsId,Headline,Content,CreateDate,LastSaveDate,PublishDate,EmailDate,Hidden")] News news)
        {
            if (ModelState.IsValid)
            {
                news.Headline = HttpUtility.HtmlEncode(news.Headline);
                news.Content = HttpUtility.HtmlEncode(news.Content);
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        [Authorize(Roles = "Admin")]
        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            news.Headline = HttpUtility.HtmlDecode(news.Headline);
            news.Content = HttpUtility.HtmlDecode(news.Content);
            return View(news);
        }

        [Authorize(Roles = "Admin")]
        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DotNet/TheatreCMS/Controllers/SponsorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheatreCMS.Models;
using TheatreCMS.Controllers;
using System.IO;

namespace TheatreCMS.Controllers
{
    
    public class SponsorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "Admin")]
        // GET: Sponsors
        public ActionResult Index()
        {          
            return View(db.Sponsors.ToList());
        }

        ////List of sponsors, partial view _Sponsors
        //public ActionResult List()
        //{
        //    return View("_Sponsors", db.Sponsors); 
        //}


        //Method for partial view 
        public ActionResult List()
        {
            return PartialView("_SponsorsPartial", db.Sponsors);
        }

        [Authorize(Roles = "Admin")]
        // GET: Sponsors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsor sponsor = db.Sponsors.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            return View(sponsor);
        }

        [Authorize(Roles = "Admin")]
        // GET: Sponsors/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Sponsors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SponsorId,Name,Height,Width,Current,Link")] Sponsor sponsor, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    //takes upload file and creates a photo.cs object from it and returns (int)photo.ID  
                    sponsor.LogoId = PhotoController.CreatePhoto(upload, "SponsorLogo_" + sponsor.Name);
                }
                db.Sponsors.Add(sponsor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sponsor);

        }

        [Authorize(Roles = "Admin")]
        // GET: Sponsors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsor sponsor = db.Sponsors.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            return View(sponsor);
        }

        [Authorize(Roles = "Admin")]
        // POST: Sponsors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SponsorId,Name,LogoId,Height,Width,Current,Link")] Sponsor sponsor, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    sponsor.LogoId = PhotoController.CreatePhoto(upload, "SponsorLogo_" + sponsor.Name);
                }

                db.Entry(sponsor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sponsor);
        }

        [Authorize(Roles = "Admin")]
        // GET: Sponsors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsor sponsor = db.Sponsors.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            return View(sponsor);
        }

        [Authorize(Roles = "Admin")]
        // POST: Sponsors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sponsor sponsor = db.Sponsors.Find(id);
            db.Sponsors.Remove(sponsor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DotNet/TheatreCMS/Views/Shared/Info.cshtml
<h3>@ViewBag.Message</h3>

DotNet/TheatreCMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Lines below (style) added by Dagmar 20200312; submenus functionality changed from hover to click, submenus are stable and do not disappear anymore -->
    <style>
        .dropdown-submenu {
            position: relative;
        }

            .dropdown-submenu a::after {
                transform: rotate(-90deg);
                position: absolute;
                right: 6px;
                top: .8em;
            }

            .dropdown-submenu .dropdown-menu {
                top: 0;
                left: 100%;
                margin-left: .1rem;
                margin-right: .1rem;
            }
    </style>
</head>
<body class="palette-body">
    @Scripts.Render("~/bundles/jquery")

    <!-- Moved loading of jquery to start of body to resolve error-->

    <nav class="palette-navbar navbar fixed-top navbar-expand-xl navbar-light" id="menu">
        <a class="navbar-brand palette-navbar-header" href="@Url.Action("Index", "Home")">
            <img class="logoImg" src="~/Content/Images/cropped-logo.png" id="logo" />
        </a>
        <!--Drop down menu button -->
        <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!--Events-->
                <li class="nav-item dropdown">
                    <a class="nav-button dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Events
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li class="dropdown-submenu">
                            <a class="dropdown-item dropdown-toggle" href="@Url.Action("Index", "Productions")">Productions</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Productions")">All</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Current", "Productions")">Current</a></li>
                            </ul>
                        </li>
                        <li><a class="dropdown-item" href="@Url.Action("Index", "CalendarEvents")">Calendar of Events</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Create", "RentalRequest")">Rentals</a></li>
                    </ul>
                </li>
                <!--Company-->
                <li class="nav-item dropdown">
                    <a class="nav-button dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Company
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="@Url.Action("About", "Home")">About</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Archive", "Home")">Archive Dashboard</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Index", "CastMembers")">Current Members</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Published", "News")">News</a></li>
                        
                    </ul>
                </li>

                <!--Admin-->
                <!--Admin button made dynamic-->


                @if (User.IsInRole("Admin"))

                {
                    <li class="nav-item dropdown">
                        <a class="nav-button dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="@Url.Action("Dashboard","Admin")">Dashboard</a></li>
                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" href="@Url.Action("Index", "Manage")">Manage Productions</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Productions")">Productions</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "CastMembers")">Cast Members</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Part")">Roles</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "ProductionPhotos")">Images</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" href="#">Manage Content</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Sponsors")">Sponsors</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "DisplayInfo")">Info</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "DisplayLinks")">Links</a></li>
                                </ul>
                            </li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "RentalRequest")">Manage Rentals</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("UserList", "Admin")">User List</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("BulkAdd", "CalendarEvents")">Add Bulk Events</a></li>
                        </ul>
                    </li>
                }

                <!--Subscriber-->
                <!--Restrict to when subscriber is logged in-->

                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-button dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Subscriber
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                            <li><a class="dropdown-item" href="@Url.Action("Index", "Dashboard", new { area = "Subscribers" })">Dashboard</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "SeasonManager", new { area = "Subscribers" })">Season Manager</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Details", "Subscriber", new { area = "Subscribers" })">Manage Subscription</a></li>


                            @*<li>@Html.ActionLink("Dashboard", "Index", "Subscribers/Dashboard", new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Season Manager", "Index", "Subscribers/SeasonManager", new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Subscriber", "Index", "Subscribers/Subscriber", new { @class = "dropdown-item" })</li>*@

                        </ul>
                    </li>
                }


            </ul>
            <div class="nav-login text-center">
                @*@Html.Partial("_LoginPartial")*@
                @Html.Action("LoginNav", "Home")
            </div>
        </div>

    </nav>

    <div class="palette-container body-content">

        @RenderBody()

    </div>
    <footer class="footer mt-auto py-3 md">
        <div class="container-fluid ml-md-auto mr-md-auto py-2 pl-md-5 pl-lg-0" id="footer--container">
            <div class="row" id="footerInner">
                <div class="col-md-4 socialMediaContainer order-lg-last px-0">
                    @*this has bootstrap class's that gets rid of padding and puts the stuff on the right on a large screen*@
                    <ul class="list-group list-group-horizontal justify-content-lg-end" id="socialMediaLinks" style="background-color: black">
                        <li class="list-group-item"><a href="https://www.facebook.com/theatrevertigo/" class="facebook"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="list-group-item"><a href="https://www.youtube.com/channel/UCFErectW0eXjMFJbBTOk0DA" class="youtube"><i class="fab fa-youtube"></i></a></li>
                        <li class="list-group-item"><a href="https://twitter.com/theatrevertigo?lang=en" class="twitter"><i class="fab fa-twitter"></i></a></li>
                        <li class="list-group-item"><a href="https://www.instagram.com/theatrevertigo/" class="instagram"><i class="fab fa-instagram"></i></a></li>
                        <li class="list-group-item pr-0"><a href="https://www.patreon.com/theatrevertigo" class="patreon"><i class="fab fa-patreon"></i></a></li> @*bootstrap gets rid of the padding on the left*@
                    </ul>
                </div>
                <div class="w-100 d-none d-md-block "></div>    @*This stacks the icons on top of the links*@
                <div class="footerNavContainer col-md-8 mr-auto float-left order-lg-1">
                    <ul class="list-group" id="navBar">
                        <li class="list-group-item pt-0 ">
                            <a class="navLink" href="@Url.Action("About", "Home")">Opportunities</a>
                        </li>
                        <li class="list-group-item pt-0 ">
                            <a class="navLink" href="@Url.Action("Published", "News")">News Items</a>
                        </li>
                        <li class="list-group-item pt-0">
                            <a class="navLink" href="@Url.Action("Contact", "Home")">Contact Info</a>
                        </li>
                        <li class="list-group-item pt-0  pr-0 mr-0">
                            <a class="navLink" href="https://app.arts-people.com/index.php?donation=verti">Donate</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="float-lg-left text-left" id="contactInfo">
                @*bootstrap classes that align text*@
                <div id="address">
                    <p id="addressPadding">
                        @*Added for css styling*@
                        2110 SE 10th AVE<br />
                        Portland, OR 97214
                    </p>
                </div>

                <div id="phoneNumbers">
                    <p id="phoneNumbersPadding">
                        @*Added for css styling*@
                        Phone Number (General)<br />
                        Phone Number (Sales)
                    </p>
                </div>
            </div>
            <div class="float-lg-right text-left mt-lg-4">
                @*Boot strap text aligning*@
                <p class="my-0">&copy; @DateTime.Now.Year</p>
            </div>
        </div>
    </footer>


    @Scripts.Render("~/bundles/fullcalendar")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/javascript")
    @RenderSection("scripts", required: false)

    <!-- Script below added by Dagmar 20200312; submenus functionality changed from hover to click, submenus are stable and do not disappear anymore -->
    <script>
        $('.dropdown-menu a.dropdown-toggle').on('click', function (e) {
            if (!$(this).next().hasClass('show')) {
                $(this).parents('.dropdown-menu').first().find('.show').removeClass('show');
            }
            var $subMenu = $(this).next('.dropdown-menu');
            $subMenu.toggleClass('show');


            $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function (e) {
                $('.dropdown-submenu .show').removeClass('show');
            });


            return false;
        });
    </script>
</body>
</html>

@*<ul class="footer-list list-group list-group-horizontal" style="background-color: black">
        <li class="list-group-item"> <a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a></li>
        <li class="list-group-item"><a href="#" class="youtube"><i class="fab fa-youtube"></i></a></li>
        <li class="list-group-item"><a href="#" class="twitter"><i class="fab fa-twitter"></i></a></li>
        <li class="list-group-item"><a href="#" class="instagram"><i class="fab fa-instagram"></i></a></li>
        <li class="list-group-item"><a href="#" class="patreon"><i class="fab fa-patreon"></i></a></li>
    </ul>*@

DotNet/TheatreCMS/Views/Shared/_Sponsors.cshtml
@model IEnumerable<TheatreCMS.Models.Sponsor>
<br/>
<br/>

<h3 class="sponsor-title">Our Sponsors</h3>
<br/>
   
    @foreach (var item in Model)
    {
        <img class="sponsor-pic" src="data:image;base64,@System.Convert.ToBase64String(item.Logo)" />
        <br/>
        <p id="sponsor-text">@Html.DisplayFor(modelItem => item.Name)</p>
         
    }

DotNet/TheatreCMS/Views/Shared/_SponsorsPartial.cshtml
@model IEnumerable<TheatreCMS.Models.Sponsor>
<div class="text-center">
    <h3 class="sponsor-title">Our Sponsors</h3>

    @foreach (var item in Model)
    {
        <figure class="sponsors-partial-column">
            @*<img class="sponsor-partial-pic" src="data:image;base64,@System.Convert.ToBase64String(item.Logo)" />*@
            <div>
                <a href="@item.Link" target="_blank">

                    <img src="@Url.Action("DisplayPhoto", "Photo", new { id = item.LogoId })" style="width:350px" alt="Sponsor Logo Image" /> @*temporary css styling*@
                </a>
            </div>
            <br />
            <figcaption class="sponsor-text">@Html.DisplayFor(modelItem => item.Name)</figcaption>
        </figure>
    }
    @*<div class="center">
        <button type="button" class="btn btn-lg sponsor-donate-btn">Donate</button>
    </div>*@

</div>




@*<div id="sponsor-body">
        <div class="synopsisTitle center">Our Proud Sponsors</div>
        <div class="center">
            <img class="sponsor-partial-pic" src="~/Content/Images/Ellyn-Bye-Logo.png" />
            <img class="sponsor-partial-pic" src="~/Content/Images/OCF-logo-in-white-with-tagline-lg.png" />
            <img class="sponsor-partial-pic" src="~/Content/Images/RACC2.png" />
            <img class="sponsor-partial-pic" src="~/Content/Images/Ninkasi-white-text.png" />
            <img class="sponsor-partial-pic" src="~/Content/Images/LogoRoundColor.png" />
        </div>
        <div class="center">
            <button type="button" class="btn btn-lg sponsor-donate-btn">Donate</button>
        </div>
    </div>*@