DotNet/TheatreCMS/Models/CalendarEvent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using TheatreCMS.Models;

namespace TheatreCMS.Models
{
    public class CalendarEvent
    {
        [Key]
        public int EventId { get; set; }            // event primary key
        public string Title { get; set; }           // event title
        [Column(TypeName="datetime2")]
        public DateTime StartDate { get; set; }     // event start date and time
        [Column(TypeName = "datetime2")]
        public DateTime EndDate { get; set; }       // event end date and time
        public int? TicketsAvailable { get; set; }  // number of tickets remaining
        public string Color { get; set; }           // event color when rendered in full calendar
        public string ClassName { get; set; }       // (remove)
        public string SomeKey { get; set; }         // (remove)
        public bool AllDay { get; set; }            // all day event

        public int? ProductionId { get; set; }      // Id for associated production

        public int? RentalRequestId { get; set; }   // Id for associated rental request
    }


}

DotNet/TheatreCMS/Controllers/CalendarEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Documents;
using TheatreCMS.Models;
using System.Web.Mvc.Html;
using System.Web.UI.WebControls;
using System.Diagnostics;
using System.Web.Script.Serialization;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;


namespace TheatreCMS.Controllers
{
    public class CalendarEventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CalendarEvents
        public ActionResult Index()
        {
            ViewData["Productions"] = new SelectList(db.Productions.ToList(), "ProductionId", "Title");
            ViewData["RentalRequests"] = new SelectList(db.RentalRequests.ToList(), "RentalRequestId", "Company");
            return View(db.CalendarEvent.ToList());
        }

        public JsonResult GetCalendarEvents()
        {
            var events = db.CalendarEvent.ToArray();

            return Json(db.CalendarEvent.Select(x => new
            {
                id = x.EventId,
                title = x.Title,
                start = x.StartDate,
                end = x.EndDate,
                seats = x.TicketsAvailable,
                color = x.Color,
                className = x.ClassName,
                someKey = x.SomeKey,
                allDay = false,
                rentalrequestid = x.RentalRequestId,//added for calendar event modals
                productionid = x.ProductionId,//added for calendar event modals
            }).ToArray(), JsonRequestBehavior.AllowGet);
        }

        // GET: CalendarEvents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalendarEvent calendarEvent = db.CalendarEvent.Find(id);
            if (calendarEvent == null)
            {
                return HttpNotFound();
            }
            return View(calendarEvent);
        }

        // GET: CalendarEvents/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {

            ViewData["Productions"] = new SelectList(db.Productions.ToList(), "ProductionId", "Title");
            ViewData["RentalRequests"] = new SelectList(db.RentalRequests.ToList(), "RentalRequestId", "Company");
            return View();


        }

        // POST: CalendarEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for  on, let me show u the 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "EventId,Title,StartDate,EndDate,TicketsAvailable,Color,ProductionId,RentalRequestId")] CalendarEvent calendarEvent)
        {          
           var isAjax = Request.IsAjaxRequest();
            if (ModelState.IsValid && !isAjax)
            {
                ViewData["Productions"] = new SelectList(db.Productions.ToList(), "ProductionId", "Title");
                ViewData["RentalRequests"] = new SelectList(db.RentalRequests.ToList(), "RentalRequestId", "Company");

                var productionID = Request.Form["Productions"];
                var rentalID = Request.Form["RentalRequests"];

                if (productionID == "" && rentalID == "")
                {
                    var validationMessage = "Please select a Production or a Rental Request.";
                    this.ModelState.AddModelError("ProductionId", validationMessage);
                    this.ModelState.AddModelError("RentalRequestId", validationMessage);
                }
                else if (productionID != "" && rentalID == "")
                {
                    calendarEvent.ProductionId = Convert.ToInt32(productionID);
                }
                else if (productionID == "" && rentalID != "")
                {
                    calendarEvent.RentalRequestId = Convert.ToInt32(rentalID);
                }
                else
                {
                    var validationMessage = "You can only select either Production or Rental Request, please try again.";
                    this.ModelState.AddModelError("ProductionId", validationMessage);
                    this.ModelState.AddModelError("RentalRequestId", validationMessage);
                }

                if (ViewData["Productions"] != null)
                    db.CalendarEvent.Add(calendarEvent);

                db.SaveChanges();
                //System.Diagnostics.Debug.WriteLine("This call was NOT made from ajax, therefore from Create MVC Page. isAjax: " + isAjax);
                return RedirectToAction("Index");              
            }
            if (ModelState.IsValid && isAjax){
                
                //System.Diagnostics.Debug.WriteLine("This call was made from Ajax, therefore from Add Modal. isAjax: " + isAjax);
                db.CalendarEvent.Add(calendarEvent);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return View(calendarEvent);
        }

        // GET: CalendarEvents/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalendarEvent calendarEvents = db.CalendarEvent.Find(id);

            if (calendarEvents == null)
            {
                return HttpNotFound();
            }
            return View(calendarEvents);
        }

        // POST: CalendarEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "EventId,Title,StartDate,EndDate,TicketsAvailable,Color,ProductionId,RentalRequestId")] CalendarEvent calendarEvents)
        {
            var isAjax = Request.IsAjaxRequest();
            if (ModelState.IsValid && !isAjax)
            {                
                db.Entry(calendarEvents).State = EntityState.Modified;
                db.SaveChanges();
                System.Diagnostics.Debug.WriteLine("This call was NOT made from ajax, therefore from Create MVC Page. isAjax: " + isAjax);
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid && isAjax)
            {
                System.Diagnostics.Debug.WriteLine("This call was made from Ajax, therefore from Add Modal. isAjax: " + isAjax);
                db.Entry(calendarEvents).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return View();
        }

        // GET: CalendarEvents/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalendarEvent calendarEvent = db.CalendarEvent.Find(id);
            if (calendarEvent == null)
            {
                return HttpNotFound();
            }
            return View(calendarEvent);
        }

        // POST: CalendarEvents/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CalendarEvent calendarEvent = db.CalendarEvent.Find(id);
            db.CalendarEvent.Remove(calendarEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // POST: CalendarEvents Confirm Delete Modal
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public JsonResult DeletingEvent(int id)
        {
            var status = false;
            CalendarEvent eventtodel = db.CalendarEvent.Where(a => a.EventId == id).FirstOrDefault();
            if (eventtodel != null)
            {
                db.CalendarEvent.Remove(eventtodel);
                db.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: CalendarEvents/BulkAdd

        [Authorize(Roles = "Admin")]
        public ActionResult BulkAdd()
        {
            ViewData["Productions"] = new SelectList(db.Productions.OrderByDescending(x => x.Season).ToList(), "ProductionId", "Title");
            ViewData["Times"] = GetTimeIntervals();
            Debug.WriteLine("BulkAdd main");
            return View();
        }

        
        [Authorize(Roles = "Admin")]
        public ActionResult GetProduction(int productionId = 0)
        {
            int id = Convert.ToInt32(productionId);
            var query = from production in db.Productions
                        where production.ProductionId == id
                        select new { production.OpeningDay, production.ClosingDay, production.ShowtimeMat, production.ShowtimeEve, production.Runtime }; /*ShowtimeMat = production.ShowtimeMat.Value.ToString("hh:mm tt"), ShowtimeEve = production.ShowtimeEve.Value.ToString*/

            return Json(JsonConvert.SerializeObject(query), JsonRequestBehavior.AllowGet);

        }

DotNet/TheatreCMS/Views/CalendarEvents/BulkAdd.cshtml
@model TheatreCMS.Models.CalendarEvent

@{
    ViewBag.Title = "Create Bulk Production Calendar Events";
}

<h2>Create Bulk Production Calendar Events</h2>

<section id="generate-showtimes-section">
    <header>Generate Showtimes</header>

    <div class="form-group">
        <label class="bulk-add--label col-md-4">Production</label>
        <div class="col-md-10 float-left formBox">
            @Html.DropDownList("Productions", (IEnumerable<SelectListItem>)ViewData["Productions"], "N/A", htmlAttributes: new { @class = "form-control", @id = "generate__production-field" })
            @Html.ValidationMessageFor(model => model.ProductionId, "", new { @class = "text-white" })
        </div>
    </div>

    <div class="form-group">
        <label class="bulk-add--label col-md-4">Start Date</label>
        <div class="col-md-10 float-left formBox">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @id = "generate__start-date-field", @type = "date" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-white" })
        </div>
    </div>

    <div class="form-group ">
        <label class="bulk-add--label col-md-4">End Date</label>
        <div class="col-md-10 float-left formBox">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker", @id = "generate__end-date-field", @type = "date" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-white" })
        </div>
    </div>

    <div class="form-group d-inline-block show-times">
        <label for="matinee">
            <input type="checkbox" id="matinee" name="matinee" />
            Matinee <span id="matinee-time"></span>
        </label>
        <label for="evening">
            <input type="checkbox" id="evening" name="evening" />
            Evening <span id="evening-time"></span>
        </label>
        <label for="other" id="showtime-dropdown">
            Custom
            @Html.DropDownList("custom-time", new SelectList(ViewData["Times"] as List<string>), "", new { @class = "dropdown" })

        </label>
    </div>


    <div class="form-group">
        <label>
            @Html.CheckBox("monday", false)
            Monday
        </label>
        <label>
            @Html.CheckBox("tuesday", false)
            Tuesday
        </label>
        <label>
            @Html.CheckBox("wednesday", false)
            Wednesday
        </label>
        <label>
            @Html.CheckBox("thursday", false)
            Thursday
        </label>
        <label>
            @Html.CheckBox("friday", false)
            Friday
        </label>
        <label>
            @Html.CheckBox("saturday", false)
            Saturday
        </label>
        <label>
            @Html.CheckBox("sunday", false)
            Sunday
        </label>
    </div>

    <div class="form-group">
        <label>
            Interval
            <select id="interval">
                <option value="1">One Week</option>
                <option value="2">Two Weeks</option>
                <option value="3">Three Weeks</option>
                <option value="4">Four Weeks</option>
            </select>
        </label>
    </div>

    <div>
        <button type="button" id="generate-button">Generate Showtimes</button>
    </div>
    
    <div id="bulk-add-modal">
        <div id="bulk-add-modal_content">
            <p>Would you like to add the following show times to the list?</p>
            <table id="modal-table">
                <tr>
                    <th>Date</th>
                    <th>Day</th>
                    <th>Start Time</th>
                </tr>

            </table>
            <button type="button" id="bulk-add-modal_yes" class="bulk-add-modal_button">YES</button>
            <button type="button" id="bulk-add-modal_no" class="bulk-add-modal_button">NO</button>
        </div>
    </div>


</section>

<section id="review-showtimes-section">

    <header>Review Showtimes</header>
    <div id="showtimes-container">
        <table id="showtimes-table">
            
                <tr>
                    <th>Date</th>
                    <th>Day</th>
                    <th>Start Time</th>
                </tr>
            
        </table>
    </div>
    <div>
        <button id="bulk-add_submit" type="submit">Submit</button>
    </div>

</section>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>













@*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>CalendarEvent</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }*@

DotNet/TheatreCMS/Views/CalendarEvents/Create.cshtml
@model TheatreCMS.Models.CalendarEvent

@{
    ViewBag.Title = "Create";
}


<h2>Create</h2>



@using (Html.BeginForm())
{
   
    @Html.AntiForgeryToken()
    <div class="formContainer2 ">
        <div class="form-horizontal">
            <h4 class="formHeader" >CalendarEvent</h4>
            <hr />
            <div class="inputBox2">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-white" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-white" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-4 inputLabel"})
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker", @type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-white" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TicketsAvailable, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.TicketsAvailable, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TicketsAvailable, "", new { @class = "text-white" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="inputLabel col-md-4"> &nbsp; &nbsp;Production</label>
                    <div class="col-md-10 formBox">
                        @Html.DropDownList("Productions", (IEnumerable<SelectListItem>)ViewData["Productions"],"N/A" , htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ProductionId,"", new { @class = "text-white" }) 
                    </div>
                </div>

                <div class="form-group">
                    <label class="inputLabel col-md-4"> &nbsp; &nbsp;Rental Request</label>
                    <div class="col-md-10 formBox">
                        
                        @Html.DropDownList("RentalRequests", (IEnumerable<SelectListItem>)ViewData["RentalRequests"],"N/A", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RentalRequestId,"", new { @class = "text-white" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 formBox">
                        <input type="submit" value="Create" class="submitButton2" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DotNet/TheatreCMS/Views/CalendarEvents/Delete.cshtml
@model TheatreCMS.Models.CalendarEvent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CalendarEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TicketsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RentalRequestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentalRequestId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DotNet/TheatreCMS/Views/CalendarEvents/Details.cshtml
@model TheatreCMS.Models.CalendarEvent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CalendarEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TicketsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RentalRequestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentalRequestId)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.EventId })
        <text>&nbsp; | &nbsp;</text>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

DotNet/TheatreCMS/Views/CalendarEvents/Edit.cshtml
@model TheatreCMS.Models.CalendarEvent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "CalendarEvents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="formContainer2 ">
        <div class="form-horizontal">
            <h4 class="formHeader">CalendarEvent</h4>
            <hr />
            @Html.Hidden("EventId", Model.EventId)
            <div class="inputBox2">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TicketsAvailable, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.TicketsAvailable, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TicketsAvailable, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductionId, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.ProductionId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ProductionId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RentalRequestId, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.RentalRequestId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RentalRequestId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 formBox">
                        <input type="submit" value="Save" class="submitButton2" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}