DotNet/TheatreCMS/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TheatreCMS.Models
{
    public class Photo
    {
        public int PhotoId { get; set; }
        public byte[] PhotoFile { get; set; }
        public int OriginalHeight { get; set; }
        public int OriginalWidth { get; set; }
        public string Title { get; set; }
    }
}

DotNet/TheatreCMS/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Media.Animation;
using TheatreCMS.Models;
using TheatreCMS.ViewModels;

namespace TheatreCMS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PhotoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Photo
        public ActionResult Index()
        {
            return View(db.Photo.ToList());
        }

        // Action method for displaying infinite scroll 
        public ActionResult GetPhotos(int pageIndex, int pageSize)
        {
            System.Threading.Thread.Sleep(500);  //sets a delay on loading. Used for debugging.
            var query = (from photo in db.Photo
                         orderby photo.PhotoId ascending
                         select new { photo.PhotoId, photo.OriginalHeight, photo.OriginalWidth, photo.Title }).Skip(pageIndex * pageSize).Take(pageSize);  // selecting anonymous type is done to prevent passing the byte array in the PhotFile attribute 

            return Json(Newtonsoft.Json.JsonConvert.SerializeObject(query), JsonRequestBehavior.AllowGet);
        }

        // GET: Photo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        //file -> byte[]
        [AllowAnonymous]
        public static byte[] ImageBytes(HttpPostedFileBase file)
        {
            //Convert the file into a System.Drawing.Image type
            Image image = Image.FromStream(file.InputStream, true, true);
            //Convert that image into a Byte Array to facilitate storing the image in a database
            var converter = new ImageConverter();
            byte[] imageBytes = (byte[])converter.ConvertTo(image, typeof(byte[]));
            //return Byte Array
            return imageBytes;
        }

        //byte[] -> smaller byte[]
        [AllowAnonymous]
        public static byte[] ImageThumbnail(byte[] imageBytes, int thumbWidth, int thumbHeight)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                Image img = Image.FromStream(new MemoryStream(imageBytes));
                using (Image thumbnail = img.GetThumbnailImage(img.Width, img.Height, null, new IntPtr()))
                {
                    thumbnail.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                    return ms.ToArray();
                }
            }
        }

        // GET: Photo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Photo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PhotoId,PhotoFile,OriginalHeight,OriginalWidth,Title")] Photo photo, HttpPostedFileBase file)
        {
            byte[] photoArray = ImageBytes(file);
            if (db.Photo.Where(x => x.PhotoFile == photoArray).ToList().Any())
            {
                var id = db.Photo.Where(x => x.PhotoFile == photoArray).ToList().FirstOrDefault().PhotoId;
                ModelState.AddModelError("PhotoFile", "This photo already exists in the database. Would you like to <a href='/Photo/Details/" + id + "'>view</a> or <a href='/Photo/Edit/" + id + "'>edit</a> the photo?");
            }
            if (ModelState.IsValid)
            {
                photo.PhotoFile = photoArray;
                Bitmap img = new Bitmap(file.InputStream);
                photo.OriginalHeight = img.Height;
                photo.OriginalWidth = img.Width;

                db.Photo.Add(photo);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(photo);
        }

        [AllowAnonymous]
        public static int CreatePhoto(HttpPostedFileBase file, string title)

        {
            var photo = new Photo();
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                photo.Title = title;
                Image image = Image.FromStream(file.InputStream, true, true);
                photo.OriginalHeight = image.Height;
                photo.OriginalWidth = image.Width;
                var converter = new ImageConverter();
                photo.PhotoFile = (byte[])converter.ConvertTo(image, typeof(byte[]));
                db.Photo.Add(photo);
                db.SaveChanges();
                return photo.PhotoId;
            }
        }

        //Takes an image file and title string and returns the PhotoId as string
        [HttpPost]
        [ValidateAntiForgeryToken]
        public string GetPhotoId(HttpPostedFileBase file, string title)
        {
            if (ModelState.IsValid)
            {
                var photo = new Photo();
                photo.Title = title;
                Image image = Image.FromStream(file.InputStream, true, true);
                photo.OriginalHeight = image.Height;
                photo.OriginalWidth = image.Width;
                var converter = new ImageConverter();
                photo.PhotoFile = (byte[])converter.ConvertTo(image, typeof(byte[]));
                db.Photo.Add(photo);
                db.SaveChanges();
                return (photo.PhotoId).ToString();
    
            }

            return null;
        }


        [AllowAnonymous]
        public ActionResult DisplayPhoto(int? id) //nullable int
        {
            string filePath = Server.MapPath(Url.Content("~/Content/Images/no-image.png"));
            Image noImageAvail = Image.FromFile(filePath);
            var converter = new ImageConverter();
            var byteData = (byte[])converter.ConvertTo(noImageAvail, typeof(byte[]));
            if (id.HasValue)
            {
                Photo photo = db.Photo.Find(id);
                if (photo == null)
                {
                    return File(byteData, "image/png");
                }
                else
                {
                    return File(photo.PhotoFile, "image/png");
                }
            }
            else
            {
                return File(byteData, "image/png");
            }
        }

        // GET: Photo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhotoId,PhotoFile,OriginalHeight,OriginalWidth,Title")] Photo photo, HttpPostedFileBase file)
        {
            var currentphoto = db.Photo.Find(photo.PhotoId);
            byte[] photoArray = ImageBytes(file);
            if (db.Photo.Where(x => x.PhotoFile == photoArray).ToList().Any())
            {
                var id = db.Photo.Where(x => x.PhotoFile == photoArray).ToList().FirstOrDefault().PhotoId;
                ModelState.AddModelError("PhotoFile", "This photo already exists in the database. Would you like to <a href='/Photo/Details/" + id + "'>view</a> the photo?");
            }
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    
                    currentphoto.PhotoFile = photoArray;
                    Bitmap img = new Bitmap(file.InputStream);
                    currentphoto.OriginalHeight = img.Height;
                    currentphoto.OriginalWidth = img.Width;
                    currentphoto.Title = photo.Title;
                    db.Entry(currentphoto).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    currentphoto.Title = photo.Title;
                    db.Entry(currentphoto).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            
            }

            return View(photo);
        }

        // GET: Photo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photo.Find(id);
            db.Photo.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

DotNet/TheatreCMS/Views/Photo/Create.cshtml
@model TheatreCMS.Models.Photo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    <div class="formContainer2 ">
        <div class="form-horizontal">
            <h4 class="formHeader">Photo</h4>
            <hr />
            <div class="inputBox2">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.TextBoxFor(model => model.PhotoFile, new { type = "file", Name = "file", Id = "PhotoFile", Class = "fileSelect" })
                        @*@Html.EditorFor(model => model.PhotoFile, new { htmlAttributes = new { @class = "form-control" } })*@
                        @*@Html.ValidationMessageFor(model => model.PhotoFile, "", new { @class = "text-danger" })*@
                        @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationMessageFor(model => model.PhotoFile, "", new { @class = "text-white" }).ToHtmlString()))
                    </div>
                </div>
                @*<div class="form-group">
            @Html.LabelFor(model => model.OriginalHeight, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-10 formBox">
                @Html.EditorFor(model => model.OriginalHeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OriginalHeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OriginalWidth, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-10 formBox">
                @Html.EditorFor(model => model.OriginalWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OriginalWidth, "", new { @class = "text-danger" })
            </div>
        </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 formBox">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}


    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

DotNet/TheatreCMS/Views/Photo/Delete.cshtml
@model TheatreCMS.Models.Photo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhotoFile)
        </dt>

        <dd>
            <img class="medium_size" src='@Url.Action("DisplayPhoto", "Photo", new { id = Model.PhotoId })' />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OriginalHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OriginalHeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OriginalWidth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OriginalWidth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DotNet/TheatreCMS/Views/Photo/Details.cshtml
@model TheatreCMS.Models.Photo

@{
    ViewBag.Title = "Details";
}


<link href="https://fonts.googleapis.com/css?family=BioRhyme&display=swap" rel="stylesheet">

<div class="photodetailspagedecorating">
 
    

    
     
<h2>Details</h2>


    
  
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhotoFile)
        </dt>
        <dd class="image-spacing" max-width: 500px>
            <img class="large_size" src='@Url.Action("DisplayPhoto", "Photo", new { id = Model.PhotoId })' />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OriginalHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OriginalHeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OriginalWidth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OriginalWidth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        @if (TheatreCMS.Controllers.PhotoController.FindDependencies(Model.PhotoId).HasDependencies == false)
        {
            <dt>
                This photo is not being used
            </dt>
        }
        else
        {
            <dt>
                This photo is being used by the following items: 
            </dt>
            <dd>
                @foreach (var production in TheatreCMS.Controllers.PhotoController.FindDependencies(Model.PhotoId).ProductionPhotos)
                {
                    @production.Title; <text> - Season: </text>
                    @production.Production.Season; <br />
                }
                @foreach (var sponsor in TheatreCMS.Controllers.PhotoController.FindDependencies(Model.PhotoId).Sponsors)
                {
                    @sponsor.Name <br />
                }
            </dd>
        }

    </dl>
</div>
      
    <p class=" backandeditspacing">
        @Html.ActionLink("Edit", "Edit", new { id = Model.PhotoId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

    

DotNet/TheatreCMS/Views/Photo/Edit.cshtml
@model TheatreCMS.Models.Photo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Photo", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="formContainer2 ">
        <div class="form-horizontal">
            <h4 class="formHeader">Photo</h4>
            <hr />
            <div class="inputBox2">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.PhotoId)

                <div class="form-group">
                    <img class="medium_size" src='@Url.Action("DisplayPhoto", "Photo", new { id = Model.PhotoId })' />
                    <p class="font-weight-bolder lead">Height :  @Html.DisplayFor(model => model.OriginalHeight) px | Width : @Html.DisplayFor(model => model.OriginalWidth) px</p>
                    @*@Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
            <div class="col-md-10 formBox">
                @Html.EditorFor(model => model.PhotoFile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhotoFile, "", new { @class = "text-danger" })
            </div>*@
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.TextBoxFor(model => model.PhotoFile, new { type = "file", Name = "file", Id = "PhotoFile", Class = "fileSelect" })
                        @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationMessageFor(model => model.PhotoFile, "", new { @class = "text-white" }).ToHtmlString()))
                        @*@Html.ValidationMessageFor(model => model.PhotoFile, "", new { @class = "text-danger" });*@
                    </div>
                </div>
                @*<div class="form-group">
            @Html.LabelFor(model => model.OriginalHeight, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
            <div class="col-md-10 formBox">
                @Html.EditorFor(model => model.OriginalHeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OriginalHeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OriginalWidth, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
            <div class="col-md-10 formBox">
                @Html.EditorFor(model => model.OriginalWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OriginalWidth, "", new { @class = "text-danger" })
            </div>
        </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-4 inputLabel" })
                    <div class="col-md-10 formBox">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <!--Will display warning message only if the photo has dependencies-->
                @if (TheatreCMS.Controllers.PhotoController.FindDependencies(Model.PhotoId).HasDependencies == true)
                {
                    <!-- Button trigger modal -->
                    <button type="button" class="submitButton2" data-toggle="modal" data-target="#exampleModalCenter">
                        Save
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Warning</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    You are trying to upload an image for a photo that has dependencies.  Are you sure you want to proceed?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button> <!--"No" button highlighted blue by default-->
                                    <button type="submit" class="btn btn-secondary" value="Save">Yes</button>

                                </div>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10 formBox">
                            <input type="submit" value="Save" class="submitButton2" />
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
}
@if (TheatreCMS.Controllers.PhotoController.FindDependencies(Model.PhotoId).HasDependencies == false)
{
    <dt>
        This photo is not being used
    </dt>
}
else
{
    <dt>
        This photo is being used by the following items:
    </dt>
    <dd>

        @foreach (var production in TheatreCMS.Controllers.PhotoController.FindDependencies(Model.PhotoId).ProductionPhotos)
        {
            @production.Title; <text> - Season: </text>
            @production.Production.Season; <br />
        }
        @foreach (var sponsor in TheatreCMS.Controllers.PhotoController.FindDependencies(Model.PhotoId).Sponsors)
        {
            @sponsor.Name <br />
        }
    </dd>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DotNet/TheatreCMS/Views/Photo/Index.cshtml
@model IEnumerable<TheatreCMS.Models.Photo>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div id="scroll-container"></div>
<table class="table-styling">
    <tr class="tr-styling">
        <th class="th-styling">
            @Html.DisplayNameFor(model => model.PhotoFile)
        </th>
        <th class="th-styling">
            @Html.DisplayNameFor(model => model.OriginalHeight)
        </th>
        <th class="th-styling">
            @Html.DisplayNameFor(model => model.OriginalWidth)
        </th>
        <th class="th-styling">
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>


                         @*below is the razor implementation used before the infinite scroll was added*@
                                         @*the table is now populated in the site.js file*@

@*@foreach (var item in Model) {
    <tr class="tr-styling">
        <td class="td-styling">
            <img id="photo-index-img-@item.PhotoId" class="photo-index-image thumbnail_size photo-index-img" 
                     onclick="ShowModel(@item.PhotoId)" src='@Url.Action("DisplayPhoto", "Photo", new { id = item.PhotoId })' />
        </td>
        <td class="td-styling">
            @Html.DisplayFor(modelItem => item.OriginalHeight)
        </td>
        <td class="td-styling">
            @Html.DisplayFor(modelItem => item.OriginalWidth)
        </td>
        <td class="td-styling">
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td class="td-styling">
            @Html.ActionLink("Edit", "Edit", new { id=item.PhotoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PhotoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PhotoId })
        </td>
    </tr>
}*@
 
                         @*Loading bar*@
</table>
                       @*Container for the photo modal*@
<div id="photo-modal" class="photo-modal">
    <img id="photo-modal--content" class="photo-modal--content" />
</div>
<div id="progress" style="display:none">
    <h4>Loading...</h4>
</div>